name: HelpCraft
main: me.soldier.codeix.HelpCraft
version: 1.7.2
commands:
    Help?:
        usage: /<command> 
    HelpEcon:
        usage: /<command> 
    HelpShop:
        usage: /<command>    
    HelpLock:
        usage: /<command> 
    HelpCmd:
        usage: /<command> 
    Helpsec:
        usage: /<command> 
    HelpMisc:
        usage: /<command> 
    HelpAdmn:
        usage: /<command> 
    HelpChat:
        usage: /<command> 
    HelpEdit:
        usage: /<command> 
    HelpWGen:
        usage: /<command> 
    HelpFun:
        usage: /<command> 
    HelpGen:
        usage: /<command> 
    HelpTp:
        usage: /<command> 
    HelpInfo:
        usage: /<command> 
    HelpMech:
        usage: /<command>
    HelpReload:
        usage: /<command> 
permissions:
    Help.user.*:
      description: Give access to all commands
      children:
        Help.helpEcon: true
        Help.helpsec: true
        Help.helplock: true
        help.help: true
        Help.helpmisc: true
        Help.helpchat: true
        help.helpshop: true
        Help.helpfun: true
        Help.helpgen: true
        Help.helptp: true
        Help.helpinfo: true
        Help.helpmech: true
        Help.helpreload: true
    Help.admn.*:
      description: Give access to all commands
      children:
        Help.helpEcon: true
        help.help: true
        Help.helpsec: true
        Help.helplock: true
        Help.helpmisc: true
        Help.helpchat: true
        Help.helpfun: true
        Help.helpgen: true
        Help.helptp: true
        Help.helpinfo: true
        Help.helpedit: true
        Help.helpwgen: true
        Helphelpadmn: true
        help.user.*: true
        Help.helpmech: true
        Help.helpreload: true

    Help.help:
        description: Give access to Help? command
        default: op
    Help.helpshop:
        description: Give access to Helpshop command
        default: op        
    Help.helpEcon:
        description: Give access to HelpMoney command
        default: op
    Help.helpsec:
        description: Give access to Helpsec command
        default: op
    Help.helplock:
        description: Give access to Helplock command
        default: op
    Help.helpmisc:
        description: Give access to HelpMoney command
        default: op
    Help.helpadmn:
        description: Give access to HelpMoney command
        default: op
    Help.helpchat:
        description: Give access to HelpMoney command
        default: op
    Help.helpedit:
        description: Give access to HelpMoney command
        default: op
    Help.helpwgen:
        description: Give access to HelpMoney command
        default: op   
    Help.helpfun:
        description: Give access to HelpMoney command
        default: op  
    Help.helpgen:
        description: Give access to HelpMoney command
        default: op
    Help.helptp:
        description: Give access to HelpMoney command
        default: op
    Help.helpinfo:
        description: Give access to HelpMoney command
        default: op
    Help.helpmech:
        description: Give access to HelpMoney command
        default: op
    Help.helpreload:
        description: Give access to HelpMoney command
        default: op